DATA:
  BATCH_SIZE: 48
  FILTER:
    MAX_DEPTH: 65
    MAX_OCCLUSION: 2
    MAX_TRUNCATION: 0.5
    MIN_DEPTH: 2
    MIN_HEIGHT: 25
  NUM_WORKERS: 4
  ROOT: /home/tienli/Desktop/monocon-pytorch/KITTI
  TEST_SPLIT: val
  TRAIN_SPLIT: train
DESCRIPTION: MonoCon Default Configuration
GPU_ID: 0
MODEL:
  BACKBONE:
    IMAGENET_PRETRAINED: true
    NUM_LAYERS: 46
  HEAD:
    MAX_OBJS: 50
    NUM_CLASSES: 3
OUTPUT_DIR: ''
PERIOD:
  EVAL_PERIOD: 20
  LOG_PERIOD: 30
SEED: 1210297989
SOLVER:
  CLIP_GRAD:
    ENABLE: true
    MAX_NORM: 35
    NORM_TYPE: 2.0
  OPTIM:
    LR: 0.00225
    NUM_EPOCHS: 300
    WEIGHT_DECAY: 1.0e-05
  SCHEDULER:
    ENABLE: true
USE_BENCHMARK: true
VERSION: v1.0.3

